pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/mangi-yeswanth/Java-Selenium-Projects.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Build & Run Tests') {
            steps {
                // Run from correct folder (only once)
                bat 'cd Capstone-Project && mvn clean test'
            }
        }

        stage('Publish Reports') {
            steps {
                // Publish JUnit results
                junit 'Capstone-Project/target/surefire-reports/*.xml'

                // Publish TestNG results
                publishTestNGResults testNGpattern: 'Capstone-Project/test-output/testng-results.xml'

                // Publish Cucumber Reports
                cucumber buildStatus: 'UNSTABLE',
                         fileIncludePattern: 'Capstone-Project/target/cucumber-reports/*.json',
                         sortingMethod: 'ALPHABETICAL'

                // Publish Extent Report
                publishHTML(target: [
                    reportDir: 'Capstone-Project/test-output/ExtentReports',
                    reportFiles: 'index.html',
                    reportName: 'Extent Report'
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'Capstone-Project/target/**/*.html', fingerprint: true
        }
    }
}
